#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xCFDF148828C642A7 (alanc@freedesktop.org)
#
Name     : xhost
Version  : 1.0.9
Release  : 11
URL      : https://www.x.org/releases/individual/app/xhost-1.0.9.tar.gz
Source0  : https://www.x.org/releases/individual/app/xhost-1.0.9.tar.gz
Source1  : https://www.x.org/releases/individual/app/xhost-1.0.9.tar.gz.sig
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: xhost-bin = %{version}-%{release}
Requires: xhost-license = %{version}-%{release}
Requires: xhost-man = %{version}-%{release}
BuildRequires : pkgconfig(x11)
BuildRequires : pkgconfig(xau)
BuildRequires : pkgconfig(xmuu)
BuildRequires : pkgconfig(xorg-macros)
BuildRequires : pkgconfig(xproto)

%description
xhost is used to manage the list of host names or user names
allowed to make connections to the X server.

%package bin
Summary: bin components for the xhost package.
Group: Binaries
Requires: xhost-license = %{version}-%{release}

%description bin
bin components for the xhost package.


%package license
Summary: license components for the xhost package.
Group: Default

%description license
license components for the xhost package.


%package man
Summary: man components for the xhost package.
Group: Default

%description man
man components for the xhost package.


%prep
%setup -q -n xhost-1.0.9
cd %{_builddir}/xhost-1.0.9

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1670944949
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1670944949
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/xhost
cp %{_builddir}/xhost-%{version}/COPYING %{buildroot}/usr/share/package-licenses/xhost/264446c12e5cd4a4f8d07212256a97c38848f90d || :
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/xhost

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/xhost/264446c12e5cd4a4f8d07212256a97c38848f90d

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/xhost.1
